indra.Web.Admin/Controllers/AdministradoresController.cs
using indra.Infra.Data;
using indra.Models;
using indra.Web.Admin.Bibliotecas;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace indra.Web.Admin.Controllers
{
    public class AdministradoresController : Controller
    {
        private readonly AgendamentoDb _context;

        public AdministradoresController(AgendamentoDb context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var admins = _context.PessoasFisicas.Where(e => e.Tipo == Models.Enums.eTipo.Administrador).OrderBy(e => e.Id).ToList();
            return View(admins);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(PessoaFisica admin)
        {
            try
            {
                if (_context.PessoasFisicas.Where(e => e.Email == admin.Email).Count() > 0)
                {
                    throw new Exception("Já existe um admin criado com o email " + admin.Email);
                }
                else
                {
                    admin.DtCriacao = DateTime.Now;
                    admin.DtAlteracao = DateTime.Now;
                    admin.Tipo = Models.Enums.eTipo.Administrador;
                    admin.Ativo = true;
                    _context.PessoasFisicas.Add(admin);
                    _context.SaveChanges();
                    TempData["S_ADM_C"] = "Administrador " + admin.Nome + " criado.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["E_ADM_C"] = e.Message;
                return View(admin);
            }
        }

        public IActionResult Editar(int id)
        {
            var admin = _context.PessoasFisicas.Find(id);
            if (admin == null)
            {
                return NotFound();
            }
            else
            {
                return View(admin);
            }
        }

        [HttpPost]
        public IActionResult Editar(PessoaFisica admin)
        {
            ViewBag.error = null;
            try
            {
                if (_context.PessoasFisicas.Where(e => e.Email == admin.Email).Count() > 0)
                {
                    throw new Exception("Já existe um profissional criado com o email " + admin.Email);
                }
                else
                {
                    admin.DtAlteracao = DateTime.Now;
                    _context.Update(admin);
                    _context.SaveChanges();
                    TempData["S_ADM_E"] = "Administrador " + admin.Nome + " editado.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["E_ADM_E"] = e.Message;
                return View(admin);
            }
        }

        public IActionResult Desativar(int id)
        {
            var admin = _context.PessoasFisicas.Find(id);
            return View(admin);
        }

        public IActionResult Ativar(int id)
        {
            ViewBag.error = null;
            try
            {
                var admin = _context.PessoasFisicas.Find(id);


                if (admin == null)
                {
                    throw new Exception("Não é possível ativar pois ele não foi encontrado");
                }
                else
                {
                    admin.DtAlteracao = DateTime.Now;
                    admin.Ativo = true;
                    _context.PessoasFisicas.Update(admin);
                    _context.SaveChanges();
                    TempData["S_ADM_A"] = "Administrador " + admin.Nome + " ativado ";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                ViewBag.error = e.Message;
                var admin = _context.PessoasFisicas.Find(id);
                TempData["E_ADM_A"] = "Erro ao ativar admin " + admin.Nome;
                return View("Index");
            }
        }

        [HttpPost]
        public IActionResult ConfirmarDesativacao(int id)
        {
            try
            {
                var admin = _context.PessoasFisicas.Find(id);
                admin.DtAlteracao = DateTime.Now;
                admin.Ativo = false;
                _context.PessoasFisicas.Update(admin);
                _context.SaveChanges();
                return Json(new { success = true, message = $"{admin.Nome} desativado." });
            }
            catch (Exception e)
            {
                return Json(new { error = true, message = $"{e.Message}" });
            }
        }

        [HttpGet]
        public IActionResult GetListaDeAdministradores(string termoDeBusca)
        {
            try
            {
                var normalizado = string.IsNullOrEmpty(termoDeBusca) ? "" : termoDeBusca.ToUpper();
                var admins = _context.PessoasFisicas.Where(c => c.Tipo == Models.Enums.eTipo.Administrador && c.Nome.ToUpper().Contains(normalizado)
                || c.Email.Contains(normalizado)
                || c.Id.ToString().Contains(normalizado)).ToList();

                var html = this.RenderizarHtmlParaString("_TabelaAdministradoresPartial", admins);
                return Json(new { success = true, html = html });
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "Falha ao buscar administradores." });
            }
        }
    }
}

indra.Web.Admin/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Threading.Tasks;
using indra.Infra.Data;
using indra.Models;
using indra.Models.Enums;
using indra.Web.Admin.Bibliotecas;
using indra.Web.Admin.Bibliotecas.Criptografia;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace indra.Web.Admin.Controllers
{
    public class ClientesController : Controller
    {
        private readonly AgendamentoDb _context;

        public ClientesController(AgendamentoDb context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var clientes = _context.PessoasFisicas.Where(e => e.Tipo == eTipo.Cliente).OrderBy(e => e.Id).ToList();
            return View(clientes);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(PessoaFisica cliente)
        {
            ViewBag.error = null;
            try
            {
                if (_context.PessoasFisicas.Where(e => e.Email == cliente.Email).Count() > 0)
                {
                    throw new Exception("Já existe um cliente com o email " + cliente.Email + " criado");
                }
                else if (_context.PessoasFisicas.Where(e => e.Cpf == cliente.Cpf).Count() > 0)
                {
                    throw new Exception("Já existe um cliente com o CPF " + cliente.Cpf + " criado");
                }
                else
                {
                    var usuario = new Usuario();
                    usuario.Login = cliente.Email;
                    usuario.Senha = cliente.Senha;
                    cliente.DtCriacao = DateTime.Now;
                    cliente.DtAlteracao = DateTime.Now;
                    cliente.Tipo = eTipo.Cliente;
                    cliente.Ativo = true;
                    usuario.PessoaFisica = cliente;
                    _context.Usuarios.Add(usuario);
                    _context.SaveChanges();
                    TempData["S_CLIE_C"] = "Cliente " + cliente.Nome + " criado.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["E_CLIE_C"] = e.Message;
                return View(cliente);
            }
        }

        public IActionResult Editar(int id)
        {
            var cliente = _context.PessoasFisicas.Find(id);
            if (cliente == null)
            {
                return NotFound();
            }
            else
            {
                return View(cliente);
            }
        }

        [HttpPost]
        public IActionResult Editar(PessoaFisica cliente)
        {
            try
            {
                if (_context.PessoasFisicas.Where(e => e.Email == cliente.Email).Count() > 0)
                {
                    throw new Exception("Já existe um profissional criado com o email " + cliente.Email);
                }
                else
                {
                    cliente.DtAlteracao = DateTime.Now;
                    _context.PessoasFisicas.Update(cliente);
                    _context.SaveChanges();
                    TempData["S_CLIE_E"] = "Cliente " + cliente.Nome + " editado.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["E_CLIE_E"] = e.Message;
                return View(cliente);
            }
        }

        public IActionResult Ativar(int id)
        {

            try
            {
                var cliente = _context.PessoasFisicas.Find(id);

                if (cliente == null)
                {
                    throw new Exception("Não é possível ativar pois ele não foi encontrado");
                }
                else
                {
                    cliente.DtAlteracao = DateTime.Now;
                    cliente.Ativo = true;
                    _context.PessoasFisicas.Update(cliente);
                    _context.SaveChanges();
                    return Json(new { success = true, message = $"{cliente.Nome} ativado." });
                }
            }
            catch (Exception e)
            {

                return Json(new { error = true, message = $"{e.Message}" });
            }
        }


        public IActionResult Desativar(int id)
        {
            var cliente = _context.PessoasFisicas.Where(e => e.Id == id).FirstOrDefault();
            return View(cliente);
        }

        [HttpPost]
        public IActionResult ConfirmarDesativacao(int id)
        {
            ViewBag.error = null;
            try
            {
                var cliente = _context.PessoasFisicas.Where(e => e.Id == id).FirstOrDefault();

                var agendamentoExistenteCliente = _context.Agendamentos.Where(e => e.ClienteId == id && e.SituacaoAgendamentoId == 1);
                if (agendamentoExistenteCliente.Count() > 0)
                {
                    throw new Exception("Não é possível desativar esse cliente pois existem agendamentos para ele.");
                }
                else
                {
                    cliente.DtAlteracao = DateTime.Now;
                    cliente.Ativo = false;
                    _context.PessoasFisicas.Update(cliente);
                    _context.SaveChanges();
                    return Json(new { success = true, message = $"{cliente.Nome} desativado." });
                }
            }
            catch (Exception e)
            {

                return Json(new { error = true, message = e.Message });
            }
        }

        [HttpGet]
        public IActionResult GetListaDeClientes(string termoDeBusca)
        {
            try
            {
                var normalizado = string.IsNullOrEmpty(termoDeBusca) ? "" : termoDeBusca.ToUpper();
                var clientes = _context.PessoasFisicas.Where(c => c.Tipo == eTipo.Cliente &&
                (c.Nome.ToUpper().Contains(normalizado)
                || c.Celular.Contains(normalizado)
                || c.Email.Contains(normalizado)
                || c.Id.ToString().Contains(normalizado))).ToList();

                var html = this.RenderizarHtmlParaString("_TabelasClientesPartial", clientes);
                return Json(new { success = true, html = html });
            }
            catch (Exception)
            {
                return Json(new { success = false, message = "Falha ao buscar clientes." });
            }
        }
    }
}

indra.Web.Admin/Controllers/ServicosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using indra.Models;
using indra.Infra.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace indra.Web.Admin.Controllers
{
    public class ServicosController : Controller
    {
        private readonly AgendamentoDb _context;

        public ServicosController(AgendamentoDb context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var servicos = _context.Servicos.OrderBy(e => e.Id).ToList();
            return View(servicos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Servico servico)
        {
            ViewBag.error = null;
            try
            {
                if (_context.Servicos.Where(e => e.Nome == servico.Nome).Count() > 0)
                {
                    throw new Exception("Serviço " + servico.Nome + " já existe");
                }
                else
                {
                    _context.Servicos.Add(servico);
                    _context.SaveChanges();
                    TempData["S_SER_C"] = "Serviço " + servico.Nome + " criado";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception e)
            {
                TempData["E_SER_C"] = e.Message;
                return View(servico);
            }
        }


        public IActionResult Editar(int id)
        {
            var servico = _context.Servicos.Find(id);
            if (servico == null)
            {
                return NotFound();
            }
            else
            {
                return View(servico);
            }
        }

        [HttpPost]
        public IActionResult Editar(Servico servico)
        {
            ViewBag.error = null;
            try
            {
                _context.Update(servico);
                _context.SaveChanges();
                TempData["S_SER_E"] = "Serviço " + servico.Nome + " editado";
                return RedirectToAction("Index");
            }
            catch (Exception e)
            {
                TempData["E_SER_E"] = e.Message;
                return View(servico);
            }
        }

        public IActionResult Excluir(int id)
        {
            var servico = _context.Servicos.Find(id);
            return View(servico);
        }

        [HttpPost]
        public IActionResult ConfirmarExclusao(int id)
        {
            try
            {
                var servico = _context.Servicos.Find(id);

                var clienteComServico = _context.Agendamentos.Where(e => e.ServicoId == id && e.SituacaoAgendamentoId == 1);
                if (clienteComServico.Count() > 0)
                {
                    throw new Exception("Não é possível excluir esse serviço pois existem clientes que o utilizam.");
                }
                else
                {
                    _context.Servicos.Remove(servico);
                    _context.SaveChanges();
                    return Json(new { excluido = true, mensagem = $"{servico.Nome} excluído." });
                }
            }
            catch (Exception e)
            {
                return Json(new { erro = true, mensagem = e.Message });
            }
        }
    }
}

indra.Web.Admin/Views/Home/AtualizarPerfil.cshtml
@model indra.Models.PessoaFisica
@inject indra.Web.Admin.Bibliotecas.LoginAdmin login

@{
    ViewData["Title"] = "Atualizar Perfil";
    var perfil = login.GetAdmin();
}

@if (TempData["E_ATUA_PERFIL"] != null)
{
    <!-- Error Alert -->
    <div class="alert alert-danger alert-dismissible fade show text-center" id="alert">
        <strong>Erro! </strong> @TempData["E_ATUA_PERFIL"]
    </div>
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col col-xs-12">
                <div class="card">
                    <div class="card-header card-header-primary titulo">
                        <h2 class="card-title"><i class="fa fa-user-circle"></i> Atualizar Perfil</h2>
                    </div>
                    <div class="card-body">
                        <br />
                        <form id="formAtualizarPerfil">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" value="@perfil.PessoaFisica.Id" />
                            <input type="hidden" asp-for="DtCriacao" value="@perfil.PessoaFisica.DtCriacao" />
                            <input type="hidden" asp-for="Tipo" value="@perfil.PessoaFisica.Tipo" />
                            <input type="hidden" asp-for="DtNascimento" value="@perfil.PessoaFisica.DtNascimento" />
                            <input type="hidden" id="sexoVal" value="@perfil.PessoaFisica.Sexo" />
                            <input type="hidden" asp-for="Ativo" value="@perfil.PessoaFisica.Ativo" />
                            <div class="row">
                                <div class="col col-xs-12">
                                    <label asp-for="Nome" class="label"></label>
                                    <div>
                                        <input value="@perfil.PessoaFisica.Nome" asp-for="Nome" class="form-control" required title="Nome é obrigatório" />
                                        <span asp-validation-for="Nome" class="text-danger col col-xs-12"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-xs-12">
                                    <label asp-for="Email" class="label"></label>
                                    <div>
                                        <input value="@perfil.PessoaFisica.Email" asp-for="Email" class="form-control" required title="Email é obrigatório" />
                                        <span asp-validation-for="Email" class="text-danger col col-xs-12"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-xs-12">
                                    <label class="label">Sexo</label>
                                    <div>
                                        <select id="Sexo" class="form-control">
                                            <option value="Masculino">Masculino</option>
                                            <option value="Feminino">Feminino</option>
                                        </select>
                                        <span asp-validation-for="Sexo" class="text-danger col col-xs-12"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-xs-12">
                                    <label asp-for="Cpf" class="label"></label>
                                    <div>
                                        <input value="@perfil.PessoaFisica.Cpf" asp-for="Cpf" id="Cpf" class="form-control" required title="Cpf é obrigatório" />
                                        <span asp-validation-for="Cpf" class="text-danger col col-xs-12"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-xs-12">
                                    <label asp-for="Celular" class="label"></label>
                                    <div>
                                        <input value="@perfil.PessoaFisica.Celular" asp-for="Celular" id="Celular" class="form-control" required title="Celular é obrigatório" />
                                        <span asp-validation-for="Celular" class="text-danger col col-xs-12"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-xs-6">
                                    <label asp-for="Senha" class="label"></label>
                                    <div>
                                        <input value="@perfil.PessoaFisica.Senha" asp-for="Senha" class="form-control" required title="Senha é obrigatória" />
                                        <span asp-validation-for="Senha" class="text-danger col col-xs-12"></span>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col col-xs-6 ">
                                    <label asp-for="ConfirmacaoSenha"></label>
                                    <div>
                                        <input value="@perfil.PessoaFisica.ConfirmacaoSenha" asp-for="ConfirmacaoSenha" class="form-control" required title="Confirmação de Senha é obrigatória" />
                                        <span asp-validation-for="ConfirmacaoSenha" class="text-danger col col-xs-12"></span>
                                    </div>
                                </div>
                            </div>

                            <div class="row">
                                <div class="col col-xs-12">
                                    <button type="button" onclick="atualizarPerfil()" class="btn btn-outline-dark btnVerde pull-right"><i class="fa fa-save"></i> Salvar</button>
                                    <a asp-action="Perfil" class="btn btn-outline-dark btnCinza pull-left"><i class="fa fa-arrow-left"></i> Voltar</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    .col-md label {
        color: black;
    }

    .form-check, label {
        font-size: 14px;
        line-height: 1.42857;
        color: #000000;
        font-weight: 400;
    }

    .bmd-form-group .form-control, .bmd-form-group label, .bmd-form-group input::placeholder {
        color: black;
    }

    .error {
        color: red;
    }

    .form-control {
        background-image: linear-gradient(to top, #00bcd4 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
        margin-top: -10px;
    }

    .form-control, .is-focused .form-control {
        background-image: linear-gradient(to top, #00bcd4 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .is-focused [class^='bmd-label'], .is-focused [class*=' bmd-label'] {
        color: #00bcd4;
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #00bcd4 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #00bcd4 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        white-space: nowrap;
        line-height: 10px;
    }
</style>

<script>
    var atualizarPerfil = function () {
        var url = '/Home/AtualizarPerfil';
        var form = $('#formAtualizarPerfil');
        var admin = {
            Id: form.find('#Id').val(),
            DtCriacao: form.find('#DtCriacao').val(),
            Ativo: form.find('#Ativo').val(),
            Nome: form.find('#Nome').val(),
            Email: form.find('#Email').val(),
            Senha: form.find('#Senha').val(),
            ConfirmacaoSenha: form.find('#ConfirmacaoSenha').val()
        };
        $.ajax({
            url: url,
            type: 'POST',
            data: { admin: admin }
        }).done(function (data) {
            if (data.success) {
                Swal.fire({
                    title: 'Sucesso!',
                    html: data.message,
                    icon: 'success'
                }).then(function () {
                    window.location.reload();
                    window.location = '/Home/Perfil';
                });
            } else {
                Swal.fire(
                    'Ops',
                    data.message,
                    'warning'
                );
            }
        });
    }

    $(document).ready(function () {
        $("#alert").hide();
        $("#alert").fadeTo(3000, 600).slideUp(600, function () {
            $("#alert").slideUp(600);
        });
    })
</script>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

indra.Web.Admin/Views/Home/Dashboard.cshtml
@using indra.Models.DTO;
@model DashboardDTO

@{ 
    ViewData["Title"] = "Dashboard";
}

<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card card-stats">
            <div class="card-header card-header-info card-header-icon">
                <div class="card-icon">
                    <i class="fa fa-address-card"></i>
                </div>
                <p class="card-category">Profissionais</p>
                <h3 class="card-title">@Model.QtdProfissionais</h3>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a asp-controller="Profissionais" asp-action="Index"><i class="fa fa-arrow-circle-o-right"></i> Ir para Profissionais</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card card-stats">
            <div class="card-header card-header-success card-header-icon">
                <div class="card-icon">
                    <i class="fa fa-user"></i>
                </div>
                <p class="card-category">Clientes</p>
                <h3 class="card-title">@Model.QtdClientes</h3>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a asp-controller="Clientes" asp-action="Index"><i class="fa fa-arrow-circle-o-right"></i> Ir para Clientes</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card card-stats">
            <div class="card-header card-header-warning card-header-icon">
                <div class="card-icon">
                    <i class="fa fa-handshake-o"></i>
                </div>
                <p class="card-category">Serviços</p>
                <h3 class="card-title">@Model.QtdServicos</h3>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a asp-controller="Servicos" asp-action="Index"><i class="fa fa-arrow-circle-o-right"></i> Ir para Serviços</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card card-stats">
            <div class="card-header card-header-danger card-header-icon">
                <div class="card-icon">
                    <i class="fa fa-calendar"></i>
                </div>
                <p class="card-category">Agendamentos</p>
                <h3 class="card-title">@Model.QtdAgendamentos</h3>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a asp-controller="Agendamentos" asp-action="Index"><i class="fa fa-arrow-circle-o-right"></i> Ir para Agendamentos</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-6 col-md-6 col-sm-12">
        <div class="card card-stats">
            <div class="card-header card-header-primary card-header-icon">
                <div class="card-icon">
                    <i class="fa fa-address-card"></i>
                </div>
                <p class="card-category">Administradores</p>
                <h3 class="card-title">@Model.QtdAdministradores</h3>
            </div>
            <div class="card-footer">
                <div class="stats">
                    <a asp-controller="Administradores" asp-action="Index"><i class="fa fa-arrow-circle-o-right"></i> Ir para Administradores</a>
                </div>
            </div>
        </div>
    </div>
</div>