indra.Web/Controllers/AtribuicaoController.cs
using indra.Infra.Data;
using indra.Infra.Extensions;
using indra.Models;
using indra.Models.Enums;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace indra.Web.Controllers
{
    public class AtribuicaoController : Controller
    {
        private readonly AgendamentoDb _context;

        public AtribuicaoController(AgendamentoDb context)
        {
            _context = context;
        }
        public IActionResult Servico()
        {
            ViewBag.Servico = new SelectList(_context.Servicos, "Id", "Nome");
            return View();
        }

        [HttpPost]
        public IActionResult Servico(ProfissionalServico atribuicao)
        {
            try
            {
                var profissionaisServico = _context.ProfissionalServicos
                    .Where(e => e.ServicoId == atribuicao.ServicoId && e.ProfissionalId == atribuicao.ProfissionalId)
                    .Include(e => e.Profissional)
                    .Include(e => e.Servico).ToList();

                if (!profissionaisServico.ContemElementos())
                {
                    _context.ProfissionalServicos.Add(atribuicao);
                    _context.SaveChanges();
                    TempData["S_ATRI_SER"] = "Serviço atribuido ao profissional com sucesso";
                    return RedirectToAction("Perfil","Home");

                }
                else
                {
                    throw new Exception("Profissional já atribuido ao serviço");
                }
            }
            catch (Exception e)
            {
                ViewBag.Servico = new SelectList(_context.Servicos, "Id", "Nome");
                TempData["E_ATRI_SER"] = e.Message;
                return View();
            }
        }
    }
}

indra.Web/Views/Atribuicao/Servico.cshtml
@model indra.Models.ProfissionalServico
@inject indra.Web.Bibliotecas.LoginPessoaFisica login

@{
    ViewData["Title"] = "Atribuição de Serviço";
    var perfil = login.GetUsuario();
}

@if (TempData["E_ATRI_SER"] != null)
{
    <!-- Error Alert -->
    <div class="alert alert-danger alert-dismissible fade show text-center" id="alert">
        <strong>Erro! </strong> @TempData["E_ATRI_SER"]
    </div>
}


<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col col-xs-12">
                <div class="card">
                    <div class="card-header card-header-primary titulo">
                        <h3 class="card-title"><i class="fa fa-user-circle"></i> Atualizar Perfil</h3>
                    </div>
                    <div class="card-body">
                        <br />
                        <form asp-action="Servico" asp-controller="Atribuicao">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="ProfissionalId" value=@perfil.PessoaFisicaId />

                            <div class="form-group">
                                <label class="control-label" id="labelServico">Serviço</label>
                                <br />
                                <br />
                                <select class="form-control" asp-items="ViewBag.Servico" asp-for="ServicoId" required></select>
                                <span asp-validation-for="ServicoId"></span>
                            </div>
                            <br />
                            <button type="submit" class="btn btnVerde pull-right "><i class="fa fa-save"></i> Salvar</button>
                            <a asp-action="Perfil" asp-controller="Home" class="btn btnCinza pull-left"><i class="fa fa-arrow-left"></i> Voltar</a>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
    #wrapper #content-wrapper #content {
        flex: 0 0 auto;
    }

    @@media (max-width: 768px) {
        #botaoResponsivo {
            float: left;
        }

        .pull-right {
            float: left;
        }

        .pull-left {
            float: right;
        }

        .btn {
            display: block;
            width: 100%;
        }
    }

    .col-md label {
        color: black;
    }

    .form-check, label {
        font-size: 14px;
        line-height: 1.42857;
        color: #000000;
        font-weight: 400;
    }

    .bmd-form-group .form-control, .bmd-form-group label, .bmd-form-group input::placeholder {
        color: black;
    }

    .error {
        color: red;
    }

    .form-control {
        background-image: linear-gradient(to top, #36b9cc 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
        margin-top: -10px;
    }

    .form-control, .is-focused .form-control {
        background-image: linear-gradient(to top, #36b9cc 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .is-focused [class^='bmd-label'], .is-focused [class*=' bmd-label'] {
        color: #00bcd4;
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #36b9cc 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #36b9cc 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control, .is-focused .form-control {
        background-image: linear-gradient(to top, #36b9cc 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
        color: black;
    }

    label#labelServico {
        font-weight: 800;
        font-size: larger;
    }
</style>

<script>
    $(document).ready(function () {
        $("#alert").hide();
        $("#alert").fadeTo(3000, 600).slideUp(600, function () {
            $("#alert").slideUp(600);
        });
    })
</script>