indra.Web/Controllers/AgendamentosController.cs
using indra.Infra.Data;
using indra.Models;
using indra.Models.Enums;
using indra.Web.Bibliotecas;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace indra.Web.Controllers
{
    public class AgendamentosController : Controller
    {
        private readonly AgendamentoDb _context;
        private readonly LoginPessoaFisica _login;
        public AgendamentosController(AgendamentoDb context, LoginPessoaFisica login)
        {
            _context = context;
            _login = login;
        }
        public IActionResult Criar()
        {
            ViewBag.Profissional = new SelectList(_context.PessoasFisicas.Where(e => e.Tipo == eTipo.Profissional), "Id", "Nome");
            ViewBag.Servico = new SelectList(_context.Servicos, "Id", "Nome");
            return View();
        }

        [HttpPost]
        public IActionResult Criar(Agendamentos agendamento)
        {
            try
            {
                var horaVerificacao = agendamento.Horario.Hour;
                var minutoVerificacao = agendamento.Horario.Minute;
                var diaVerificacao = agendamento.Horario.Day;
                var mesVerificacao = agendamento.Horario.Month;
                var anoVerificacao = agendamento.Horario.Year;

                var qtdAgendamentosMarcados = _context.Agendamentos.Where(e =>
                    e.ProfissionalId == agendamento.ProfissionalId &&
                    e.Horario.Hour == horaVerificacao &&
                    e.Horario.Minute == minutoVerificacao &&
                    e.Horario.Day == diaVerificacao &&
                    e.Horario.Month == mesVerificacao &&
                    e.Horario.Year == anoVerificacao &&
                    e.SituacaoAgendamentoId == 1);

                if (qtdAgendamentosMarcados.Count() >= 10)
                {
                    throw new Exception("Não é possível realizar mais de 10 agendamentos por dia para o profissional " + agendamento.Profissional.Nome);
                }

                var clienteJaAgendado = _context.Agendamentos.Where(e =>
                    e.ClienteId == agendamento.ClienteId &&
                    e.Horario.Hour == horaVerificacao &&
                    e.Horario.Minute == minutoVerificacao &&
                    e.Horario.Day == diaVerificacao &&
                    e.Horario.Month == mesVerificacao &&
                    e.Horario.Year == anoVerificacao &&
                    e.SituacaoAgendamentoId == 1);

                if (clienteJaAgendado.Count() > 0)
                {
                    throw new Exception("Já existe um agendamento nesse horário.");
                }
                else
                {
                    //agendamento.ClienteId = _login.GetUsuario().PessoaFisicaId;
                    _context.Agendamentos.Add(agendamento);
                    _context.SaveChanges();
                    return Json(new { success = true, message = $"Agendamento marcado com sucesso." });
                }
            }
            catch (Exception e)
            {
                ViewBag.Profissional = new SelectList(_context.PessoasFisicas.Where(e => e.Tipo == eTipo.Profissional), "Id", "Nome");
                ViewBag.Servico = new SelectList(_context.Servicos, "Id", "Nome");
                return Json(new { erro = true, message = $"{e.Message}" });
            }
        }

        public IActionResult Editar(int id)
        {
            var agendamento = _context.Agendamentos.Find(id);
            if (agendamento == null)
            {
                return NotFound();
            }
            else
            {
                ViewBag.Profissional = _context.PessoasFisicas.Where(e => e.Id == agendamento.ProfissionalId && e.Tipo == eTipo.Profissional).FirstOrDefault();
                ViewBag.Servico = _context.Servicos.Where(e => e.Id == agendamento.ServicoId).FirstOrDefault();
                return View(agendamento);
            }
        }

        [HttpPost]
        public IActionResult Editar(Agendamentos agendamento)
        {
            try
            {
                var horaVerificacao = agendamento.Horario.Hour;
                var minutoVerificacao = agendamento.Horario.Minute;

                var clienteJaAgendado = _context.Agendamentos.Where(e =>
                    e.ClienteId == agendamento.ClienteId &&
                    e.Horario.Hour == horaVerificacao &&
                    e.Horario.Minute == minutoVerificacao &&
                    e.SituacaoAgendamentoId == 1);

                if (clienteJaAgendado.Count() > 0)
                {
                    throw new Exception("Já existe um agendamento nesse horário.");
                }
                else
                {
                    agendamento.ClienteId = _login.GetUsuario().PessoaFisicaId;
                    _context.Update(agendamento);
                    _context.SaveChanges();
                    TempData["S_AGENDA_E"] = "Agendamento editado";
                    return RedirectToAction("TelaPrincipal","Home");
                }
            }
            catch (Exception e)
            {
                ViewBag.Profissional = _context.PessoasFisicas.Where(e => e.Id == agendamento.ProfissionalId && e.Tipo == eTipo.Profissional).FirstOrDefault();
                ViewBag.Servico = _context.Servicos.Where(e => e.Id == agendamento.ServicoId).FirstOrDefault();
                TempData["S_AGENDA_E"] = e.Message;
                return View(agendamento);
            }
        }

        [HttpGet]
        public IActionResult GetDadosServico(int id)
        {
            try
            {
                var servico = _context.Servicos.Find(id);
                if (servico == null)
                {
                    throw new Exception("Serviço não encontrado");
                }
                var profissionais = _context.ProfissionalServicos.Where(e => e.ServicoId == id).Include(e => e.Profissional).ToList();
                if (!profissionais.Any())
                {
                    throw new Exception("Profissional não encontrado");
                }//seu problema resolvido, zuera que era só isso 

                return Json(new { success = true, valor = servico.Valor, profissionais = profissionais.Select(c => new { Id = c.Profissional.Id, Nome = c.Profissional.Nome }) });

            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = ex.Message });
            }
        }

        // Conclui o agendamento mudando o ID da Situação do Agendamento para Concluído
        public IActionResult Concluir(int id)
        {
            try
            {
                var agendamento = _context.Agendamentos.FirstOrDefault(c => c.Id == id);
                var horario = _context.Agendamentos.Where(e => e.Id == id).Include(e => e.Profissional).Include(e => e.Cliente).Include(e => e.Servico).Include(e => e.SituacaoAgendamento);
                if (agendamento == null)
                {
                    throw new Exception("Não foi possível concluir o agendamento, por favor recarregue a página e tente novamente.");
                }

                agendamento.SituacaoAgendamentoId = 2;
                _context.Update(agendamento);
                _context.SaveChanges();
                return Json(new { success = true, message = $"O agendamento foi concluido." });
            }
            catch (Exception e)
            {
                return Json(new { error = true, message = $"{e.Message}" });
            }
        }

        // Cancela o agendamento mudando o ID da Situação do Agendamento para Cancelado
        public IActionResult Cancelar(int id)
        {
            try
            {
                var agendamento = _context.Agendamentos.Find(id);
                if (agendamento == null)
                {
                    throw new Exception("Não foi possível cancelar o agendamento, favor recarregue a página e tente novamente.");
                }
                agendamento.SituacaoAgendamentoId = 3;
                _context.Agendamentos.Update(agendamento);
                _context.SaveChanges();
                return Json(new { success = true, message = $"O agendamento foi cancelado." });
            }
            catch (Exception e)
            {
                return Json(new { erro = true, message = $"{e.Message}" });
            }
        }

        [HttpPost]
        public IActionResult ConfirmarCancelamento(int id)
        {

            try
            {
                var agendamento = _context.Agendamentos.Find(id);

                if (agendamento == null)
                {
                    throw new Exception("Não foi possível cancelar o agendamento, favor recarregue a página e tente novamente.");
                }
                agendamento.SituacaoAgendamentoId = 3;
                _context.Agendamentos.Update(agendamento);
                _context.SaveChanges();
                return Json(new { success = true, message = $"O agendamento do cliente {agendamento.Cliente.Nome} foi cancelado." });
            }
            catch (Exception e)
            {
                return Json(new { erro = true, message = $"{e.Message}" });
            }
        }
    }
}

indra.Web/Views/Agendamentos/Cancelar.cshtml
@model indra.Models.Agendamentos

@{
    ViewData["Title"] = "Agendamento";
    var error = ViewBag.error;
}

<h1>Cancelar Agendamento</h1>

<h3>Deseja realmente cancelar esse agendamento?</h3>
<div>

    <hr />
    @if (TempData["E_AGENDA_C"] != null)
    {
        <!-- Error Alert -->
        <div class="alert alert-danger alert-dismissible fade show text-center" id="alert">
            <strong>Erro! </strong> @TempData["E_AGENDA_C"]
        </div>
    }

    <dl class="row">
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Cliente.Nome)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Cliente.Nome)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Profissional.Nome)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Profissional.Nome)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Servico.Nome)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Servico.Nome)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.Horario)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.Horario)
        </dd>
        <dt class="col-sm-3">
            @Html.DisplayNameFor(model => model.SituacaoAgendamento.Situacao)
        </dt>
        <dd class="col-sm-9">
            @Html.DisplayFor(model => model.SituacaoAgendamento.Situacao)
        </dd>

    </dl>
    <form asp-action="ConfirmarCancelamento">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Confirmar" class="btn btn-danger" />

    </form>
    <a asp-action="Index">
        <button class="btn btn-primary mt-2"
                style="background: linear-gradient( 60deg, #00bcd4, #216cca);border: 0px">
            Cancelar
        </button>
    </a>
</div>

<style>
    #wrapper #content-wrapper #content {
        flex: 0 0 auto;
    }
    .col-md label {
        color: black;
    }

    .form-control {
        background-image: linear-gradient(to top, #00bcd4 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control, .is-focused .form-control {
        background-image: linear-gradient(to top, #00bcd4 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .is-focused [class^='bmd-label'], .is-focused [class*=' bmd-label'] {
        color: #00bcd4;
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #00bcd4 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #00bcd4 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        white-space: nowrap;
        line-height: 10px;
    }
</style>

<script>
    $(document).ready(function () {
        $("#alert").hide();
        $("#alert").fadeTo(3000, 600).slideUp(600, function () {
            $("#alert").slideUp(600);
        });
    })
</script>

indra.Web/Views/Agendamentos/Concluir.cshtml
@model indra.Models.Agendamentos

@{
    ViewData["Title"] = "Agendamento";
}
<h4>Agendamento</h4>
<hr />
@if (TempData["ERRO_AGENDAMENTO_EDITAR"] != null)
{
    <!-- Error Alert -->
    <div class="alert alert-danger alert-dismissible fade show text-center" id="alert">
        <strong>Erro! </strong> @TempData["ERRO_CLIENTE_EDITAR"]
    </div>
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="Cliente.Nome" />
            <input type="hidden" asp-for="Profissional.Nome" />
            <input type="hidden" asp-for="Servico.Nome" />
            <div class="form-group">
                <label asp-for="Cliente.Nome" class="control-label"></label>
                <select asp-for="Cliente.Nome" class="form-control" asp-items="ViewBag.Cliente" disabled></select>
                <span asp-validation-for="ClienteId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Profissional.Nome" class="control-label"></label>
                <select asp-for="Profissional.Nome" class="form-control" asp-items="ViewBag.Profissional" disabled></select>
                <span asp-validation-for="ProfissionalId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Servico.Nome" class="control-label"></label>
                <select asp-for="Servico.Nome" class="form-control" asp-items="ViewBag.Servico" disabled></select>
                <span asp-validation-for="ServicoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Horario" class="control-label"></label>
                <input asp-for="Horario" class="form-control" />
                <span asp-validation-for="Horario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SituacaoAgendamento.Situacao" class="control-label"></label>
                <select asp-for="SituacaoAgendamento.Situacao" class="form-control" asp-items="ViewBag.SituacaoAgendamento"></select>
                <span asp-validation-for="SituacaoAgendamentoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" style="background-color: #00bcd4;border: 0px">Salvar</button>
                <a asp-action="Index"><button type="button" class="btn btn-danger" style="background-color: #00bcd4; border: 0px">Cancelar</button></a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

<style>
    #wrapper #content-wrapper #content {
        flex: 0 0 auto;
    }
    .col-md label {
        color: black;
    }

    .form-control {
        background-image: linear-gradient(to top, #00bcd4 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control, .is-focused .form-control {
        background-image: linear-gradient(to top, #00bcd4 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .is-focused [class^='bmd-label'], .is-focused [class*=' bmd-label'] {
        color: #00bcd4;
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #00bcd4 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #00bcd4 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        white-space: nowrap;
        line-height: 10px;
    }
</style>

<script>
    $(document).ready(function () {
        $("#alert").hide();
        $("#alert").fadeTo(3000, 600).slideUp(600, function () {
            $("#alert").slideUp(600);
        });
    })
</script>

indra.Web/Views/Agendamentos/Criar.cshtml
@*@model IEnumerable<indra.Models.Agendamentos>*@
@model indra.Models.Agendamentos 
@inject indra.Web.Bibliotecas.LoginPessoaFisica pessoa

@{
    ViewData["Title"] = "Agendamento";
    var cliente = pessoa.GetUsuario();
}
@if (TempData["E_AGENDA_C"] != null)
{
    <!-- Error Alert -->
    <div class="alert alert-danger alert-dismissible fade show text-center" id="alert">
        <strong>Erro! </strong> @TempData["E_AGENDA_C"]
    </div>
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col col-xs-12">
                <div class="card">
                    <div class="card-header card-header-primary titulo">
                        <h3 class="card-title"><i class="fa fa-plus-circle"></i> Novo Agendamento</h3>
                    </div>

                    <div class="card-body">
                        <br />
                        <form id="formCriar">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="SituacaoAgendamentoId" value="1" />
                            <input type="hidden" asp-for="ClienteId" value="@cliente.PessoaFisica.Id" />
                            <div class="form-group">
                                <label class="control-label" id="labelAgendamento">Serviço</label>
                                @Html.DropDownList("ServicoId", ViewBag.Servico, "", new
                           {
                               @class = "form-control"
                           })
                                <span asp-validation-for="ServicoId"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label class="control-label" id="labelAgendamento">Profissional</label>
                                <select class="form-control" asp-for="ProfissionalId"></select>
                                <span asp-validation-for="ProfissionalId"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label class="control-label" id="labelAgendamento">Horário</label>
                                <input asp-for="Horario" class="form-control horario" />
                                <span asp-validation-for="Horario"></span>
                            </div>
                            <br />
                            <div class="form-group">
                                <label class="control-label" id="labelAgendamento"><i class="fa fa-dollar"></i> Valor</label>
                                <br />
                                <span id="valorServico" class="valores"></span>
                            </div>
                            <br />
                            <br />
                            <button type="button" onclick="criarAgendamento()" class="btn btnVerde pull-right"><i class="fa fa-save"></i> Salvar</button>
                            <a asp-action="TelaPrincipal" asp-controller="Home" class="btn btnCinza pull-left"><i class="fa fa-arrow-left"></i> Voltar</a>
                        </form>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    #wrapper #content-wrapper #content {
        flex: 0 0 auto;
    }
    .valores {
        color: #36b9cc;
        margin-left: 0px;
        font-size: x-large;
        font-weight: 800;
    }

    #labelAgendamento {
        font-size: inherit;
        margin-top: 2px;
    }

    .horario {
        color: black;
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
        color: black;
    }

    .bmd-form-group .form-control, .bmd-form-group label, .bmd-form-group input::placeholder {
        line-height: 1.1;
        color: black;
    }

    .form-check, label {
        font-size: 14px;
        line-height: 1.42857;
        color: #000000;
        font-weight: 400;
        font-weight: bold;
    }

    .col-md label {
        color: black;
    }

    .form-control {
        background-image: linear-gradient(to top, #36b9cc 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control, .is-focused .form-control {
        background-image: linear-gradient(to top, #36b9cc 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .is-focused [class^='bmd-label'], .is-focused [class*=' bmd-label'] {
        color: #36b9cc;
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #36b9cc 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #36b9cc 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .btn-secondary {
        background-color: #5a5c69;
    }

    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        white-space: nowrap;
        line-height: 10px;
    }
</style>

<script>

    var criarAgendamento = function () {
        var url = '/Agendamentos/Criar';
        var form = $('#formCriar');
        var agendamento = {
            /*Id: form.find('#Id').val(),*/
            ClienteId: form.find('#ClienteId').val(),
            ProfissionalId: form.find('#ProfissionalId').val(),
            ServicoId: form.find('#ServicoId').val(),
            Horario: form.find('#Horario').val(),
            SituacaoAgendamentoId: form.find('#SituacaoAgendamentoId').val()
        };
        $.ajax({
            url: url,
            type: 'POST',
            data: { agendamento: agendamento }
        }).done(function (data) {
            if (data.success) {
                Swal.fire({
                    title: 'Sucesso!',
                    html: data.message,
                    icon: 'success'
                }).then(function () {
                    window.location.reload();
                    window.location = '/Home/TelaPrincipal';
                });
            } else {
                Swal.fire(
                    'Ops',
                    data.message,
                    'warning'
                );
            }
        });
    }

    $(document).ready(function () {
        $("#alert").hide();
        $("#alert").fadeTo(3000, 600).slideUp(600, function () {
            $("#alert").slideUp(600);
        });

        $('#ServicoId').on('change', function () {
            var id = $(this).val();
            if (id) {
                var url = '/Agendamentos/GetDadosServico';
                $.ajax({
                    url: url,
                    type: 'GET',
                    data: { id }
                }).done(function (retorno) {
                    if (retorno.success) {
                        $('#valorServico').text('R$ ' + retorno.valor.toFixed(2));
                        var select = $('#ProfissionalId');
                        select.html('');
                        $.each(retorno.profissionais, function (i, profissional) {
                            select.append('<option value="' + profissional.id + '">' + profissional.nome + '</option>');
                        });
                    } else {
                        Swal.fire(
                            'Ops',
                            data.message,
                            'warning'
                        );
                    }
                });
            }
        });

        $('#horario').on('change', function () {
            debugger;
            if ($('#horario').val()) {
                if (new Date($('#horario').val()) < new Date()) {
                    Swal.fire({
                        title: 'Informação!',
                        html: 'Data informada menor do que data atual',
                        icon: 'warning'
                    });
                    $('#horario').val('');
                }
            }
        });
    });

</script>

indra.Web/Views/Agendamentos/Editar.cshtml
@model indra.Models.Agendamentos

@inject indra.Web.Bibliotecas.LoginPessoaFisica pessoa

@{
    ViewData["Title"] = "Agendamento";
    var cliente = pessoa.GetUsuario();
    var servico = (indra.Models.Servico)ViewBag.Servico;
    var profissional = (indra.Models.PessoaFisica)ViewBag.Profissional;
}
@if (TempData["E_AGENDA_C"] != null)
{
    <!-- Error Alert -->
    <div class="alert alert-danger alert-dismissible fade show text-center" id="alert">
        <strong>Erro! </strong> @TempData["E_AGENDA_C"]
    </div>
}

<div class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col col-xs-12">
                <div class="card">
                    <div class="card-header card-header-primary titulo">
                        <h3 class="card-title"><i class="fa fa-plus-circle"></i> Editar Agendamento</h3>
                    </div>

                    <div class="card-body">
                        <br />
                        <form asp-action="Editar" asp-controller="Agendamentos">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <input type="hidden" asp-for="Id" />
                            <input type="hidden" asp-for="SituacaoAgendamentoId" value="1" />
                            <input type="hidden" asp-for="ClienteId" />
                            <input type="hidden" asp-for="ProfissionalId" />
                            <input type="hidden" asp-for="ServicoId" />
                            <div class="form-group">
                                <label id="labelAgendamento" class="control-label">Serviço</label>
                                <br />
                                <span>@servico.Nome</span>
                            </div>
                            <div class="form-group">
                                <label id="labelAgendamento" class="control-label">Profissional</label>
                                <br />
                                <span>@profissional.Nome</span>
                            </div>
                            <div class="form-group">
                                <label id="labelAgendamento" class="control-label">Horário</label>
                                <input asp-for="Horario" class="form-control" />
                                <span asp-validation-for="Horario"></span>
                            </div>
                            <div class="form-group">
                                <label id="labelAgendamento" class="control-label"><i class="fa fa-dollar"></i> Valor</label>
                                <br />
                                <span id="valorServico" class="valores">R$ @servico.Valor.ToString("F")</span>
                            </div>
                            <br />
                            <br />
                            <button type="submit" class="btn btnVerde pull-right"><i class="fa fa-edit"></i> Editar</button>
                            <a asp-action="TelaPrincipal" asp-controller="Home" class="btn btnCinza pull-left"><i class="fa fa-arrow-left"></i> Voltar</a>
                        </form>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<style>
    #wrapper #content-wrapper #content {
        flex: 0 0 auto;
    }
    span {
        color: #36b9cc;
        margin-left: 0px;
        font-size: x-large;
        font-weight: 800;
    }

    #labelAgendamento {
        font-size: inherit;
        margin-top: 2px;
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
        color: black;
        margin-left: -13px;
    }

    .bmd-form-group .form-control, .bmd-form-group label, .bmd-form-group input::placeholder {
        line-height: 1.1;
        color: black;
    }

    .form-check, label {
        font-size: 14px;
        line-height: 1.42857;
        color: #000000;
        font-weight: 400;
        font-weight: bold;
    }

    .col-md label {
        color: black;
    }

    .form-control {
        background-image: linear-gradient(to top, #36b9cc 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control, .is-focused .form-control {
        background-image: linear-gradient(to top, #36b9cc 2px, rgba(156, 39, 176, 0) 2px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .is-focused [class^='bmd-label'], .is-focused [class*=' bmd-label'] {
        color: #36b9cc;
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    select.form-control:not([size]):not([multiple]) {
        height: calc(2.4375rem + 2px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #36b9cc 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .form-control:read-only {
        background-image: linear-gradient(to top, #36b9cc 1px, rgba(210, 210, 210, 0) 1px), linear-gradient(to top, #333333 1px, rgba(210, 210, 210, 0) 1px);
    }

    .btn-secondary {
        background-color: #5a5c69;
    }

    .footer {
        position: absolute;
        bottom: 0;
        width: 100%;
        white-space: nowrap;
        line-height: 10px;
    }
</style>

<script>
    $(document).ready(function () {
        $("#alert").hide();
        $("#alert").fadeTo(3000, 600).slideUp(600, function () {
            $("#alert").slideUp(600);
        });
</script>